window_days: 3

filters:
  title_exclude_keywords:
    - 业绩说明会
    - 回购注销

stocks:
  - market: sz
    code: "300639"
    keywords: []
    exclude_keywords:
      - 调研

  - market: hk
    code: "00700"
    keywords: []
    exclude_keywords: []
